# General player
general:
  # Language
  # Pre translated:
  # English: en-US
  language: 'en-US'
  # Worlds were players can create farms.
  # NOTE: This setting requires server reload.
  # World names are CASE-SENSITIVE
  worlds_list:
    - world

# Database player
database:
  # MySQL
  mysql:
    # Enable this to use MySQL instead of "file based"
    # SQLite. For performance improvement it's recommended to
    # use MySQL. If you don't have access to a MySQL server,
    # just let this disabled (false).
    enabled: false
    ip-address: 'localhost'
    port: '3306'
    database: 'betterfarming'
    user: 'minecraft'
    password: 'password'

# Economy player
economy:
  # Here you can choose which type
  # of economy you want to use.
  # Highest priority is at the top.
  # If nothing could be enabled,
  # the plugin, will use item based economy.
  type:
    # Enable vault economy?
    vault: true
    # Let your players pay with
    # exp LEVELS?
    exp-levels: false
    # Default economy
    # Will be used if vault and exp is disabled
    # or no vault plugin was found and exp is disabled.
    # Set the currency item for
    # default item based economy.
    default: 'DIAMOND'

integration:
  # Plugin: Lands
  # https://www.spigotmc.org/resources/53313
  # Allow players, which are trusted in the land where the
  # farm is located in, to break blocks, place blocks and
  # interact, if they're allowed to do so in the land?
  lands: true
  # Plugin: Towny
  # Allow players, which are trusted in the town where the
  # farm is located in, to break blocks, place blocks and
  # interact, if they're allowed to do so in the town?
  towny: true

command:
  # Should players need to confirm their purchase at /Hoppers get?
  get-confirm: true
  # Set aliases
  # for /BetterFarming command
  # NOTE: This player
  # requires /reload
  aliases_list:
    - farm
    - farms
    - bf

farm:
  # Item to create farm
  item:
    # Cost of the item,
    # if you're taking it from
    # /Farm get
    cost: 1500.0
  # Creation player
  creation:
    # Should only the owner
    # registered on the farm
    # item, be able to place the farm?
    only-owner: true
    # If enabled, BetterFarming
    # will set farmland around the farm.
    farm-land: true
  # Protection player
  protection:
    # Y-plus means the y value
    # (height where the farm is) plus this value.
    # This create a protection box for the farm.
    y-plus: 4
    # Some for minus, just
    # that it goes for example 4 blocks
    # down, instead of up.
    y-minus: 4

  # DEFAULT player player
  # They will only apply for new farms.
  role:
    gardener:
      settings-gardener_list:
        - HARVEST
        - PLANT
        - BLOCK_BREAK
        - BLOCK_PLACE
        - INTERACT
    visitor:
      settings-visitor_list: []

# Crop Settings
crop:
  wheat:
    # Enable growth and harvesting of this crop?
    enabled_2: true
    # Chances (% - Percent)
    # You can play with this player
    # to make the growth and harvesting
    # of crops more rare or often.
    chance:
      # Growth
      grow_2: 100
      # Harvesting
      harvest_2: 100
  carrots:
    enabled_3: true
    chance:
      grow_3: 100
      harvest_3: 100
  potatoes:
    enabled_4: true
    chance:
      grow_4: 100
      harvest_4: 100
  beetroots:
    enabled_5: true
    chance:
      grow_5: 75
      harvest_5: 100
  melons:
    enabled_6: true
    chance:
      grow_6: 50
      harvest_6: 75
  pumpkins:
    enabled_7: true
    chance:
      grow_7: 50
      harvest_7: 75
  sweet-berries:
    enabled_8: true
    chance:
      grow_8: 75
      harvest_8: 50
  nether-wart:
    enabled_9: true
    chance:
      grow_9: 45
      harvest_9: 50

