main: me.angeschossen.betterfarming.BetterFarming
name: BetterFarming
version: 1.5.3
api-version: 1.13

commands:
  betterfarming:
    aliases: [farm, farms, farming]
    description: BetterFarming main command.

permissions:
  betterfarming.*:
    description: Access to all Betterfarming actions
    default: op
    children:
      betterfarming.farms.<Number>:
        description: Give players permission to create specific amount of farms.
        default: op

